Fk-3
pdybowski/news-app pull request #12
Opened 2021-12-02 17:58 UTC by FilipKaczmarek

2021-12-02 17:59 UTC, FilipKaczmarek commented
- Background image added
- HTML Structure Created 
- Home Module JS Created and imported to index.js
- Added content - time and date

2021-12-03 14:53 UTC, pdybowski requested changes
please fix

2021-12-03 14:53 UTC, pdybowski commented on src/JSmodules/Home.js
> +            this.fullDate = new Date();
I will recomend to put this interval in separate method e.g. _timer() or something like this

2021-12-03 14:53 UTC, pdybowski commented on src/index.js
> +homePageUpdate.start()
dont you run start function twice? in a class constructor and here

2021-12-03 14:53 UTC, pdybowski commented on src/index.html
> +            <main id="main" class="container-lg">
we are going to inject main content dynamically. Each view will be injected here (probably here) so when user switches to another view your content will be removed and never dislayed again

2021-12-04 15:23 UTC, FilipKaczmarek commented
@pdybowski changes have been made

2021-12-05 21:58 UTC, pdybowski commented
please change the UI for the one I asked on discord

2021-12-06 17:56 UTC, merged