[tp-36]-gov-requests
pdybowski/news-app pull request #59
Opened 2021-12-14 22:38 UTC by altNameForStudying

* adds `search` as main query
* adds option to search by query
* adds pagination with default values
* adds option to filter by model types
* adds option to sort by title/date/views_count

No image preview - govApi will trigger requests based on view's needs

Will probably get expanded based on Gov tab needs.

2021-12-14 22:42 UTC, pdybowski requested changes
please fix

2021-12-14 22:42 UTC, pdybowski commented on src/modules/gov/govApi.js
> +export class WeatherApi extends API {
?

2021-12-14 23:53 UTC, altNameForStudying commented on src/modules/gov/govApi.js
> +export class WeatherApi extends API {
Fixed in 51032e2

2021-12-15 00:14 UTC, pdybowski approved these changes

2021-12-15 00:14 UTC, merged